
package com.htc.lib1.cs.push;

import java.util.UUID;

import android.text.TextUtils;

import com.google.gson.annotations.SerializedName;

public class RegisterPayload extends UpdateRegisterPayload {
    private static final long serialVersionUID = 1L;

    /**
     * Optional customer ID for HTC devices.
     */
    @SerializedName("cid")
    public String customerId;

    /**
     * Device serial number.
     */
    @SerializedName("device_sn")
    public String deviceSerialNum;

    /**
     * Android ID generated by the device to distinguish Android devices.
     */
    @SerializedName("android_id")
    public String androidId;

    /**
     * Optional model ID for HTC devices.
     */
    @SerializedName("model_id")
    public String modelId;

    /**
     * Manufacturer of the device.
     */
    @SerializedName("manufacturer")
    public String manufacturer;

    /**
     * UUID generated by the client app to distinguish different clients across
     * multiple devices.
     */
    @SerializedName("client_sn")
    public UUID clientUuid;
    
    @Override
    public boolean isValid() {
        return super.isValid() && !TextUtils.isEmpty(androidId) && clientUuid != null;
    }

}
