/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_morphoinc_app_hyperlapse_engine_Engine2 */

#ifndef _Included_com_morphoinc_app_hyperlapse_engine_Engine2
#define _Included_com_morphoinc_app_hyperlapse_engine_Engine2
#ifdef __cplusplus
extern "C" {
#endif
#undef com_morphoinc_app_hyperlapse_engine_Engine2_MODE_SOFT
#define com_morphoinc_app_hyperlapse_engine_Engine2_MODE_SOFT 0L
#undef com_morphoinc_app_hyperlapse_engine_Engine2_MODE_HYBRID
#define com_morphoinc_app_hyperlapse_engine_Engine2_MODE_HYBRID 1L
#undef com_morphoinc_app_hyperlapse_engine_Engine2_MODE_HARD
#define com_morphoinc_app_hyperlapse_engine_Engine2_MODE_HARD 2L
#undef com_morphoinc_app_hyperlapse_engine_Engine2_ACCURACY_HIGH
#define com_morphoinc_app_hyperlapse_engine_Engine2_ACCURACY_HIGH 0L
#undef com_morphoinc_app_hyperlapse_engine_Engine2_ACCURACY_MIDDLE
#define com_morphoinc_app_hyperlapse_engine_Engine2_ACCURACY_MIDDLE 1L
#undef com_morphoinc_app_hyperlapse_engine_Engine2_ACCURACY_LOW
#define com_morphoinc_app_hyperlapse_engine_Engine2_ACCURACY_LOW 2L
/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    setModeJni
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_setModeJni
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    activateOisModeJni
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_activateOisModeJni
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    setGyroTimeLagJni
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_setGyroTimeLagJni
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    setVerticalViewAngleJni
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_setVerticalViewAngleJni
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    setRollingShutterCoeffJni
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_setRollingShutterCoeffJni
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    setUnreliableLevelJni
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_setUnreliableLevelJni
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    setNoMovementLevelJni
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_setNoMovementLevelJni
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    addGyroDataJni
 * Signature: (JDDDJ)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_addGyroDataJni
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    addAccelerometerDataJni
 * Signature: (JDDDJ)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_addAccelerometerDataJni
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    initializePreprocessJni
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_initializePreprocessJni
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    initializePreprocessExJni
 * Signature: (IIIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_initializePreprocessExJni
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    startPreprocessJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_startPreprocessJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    preprocessJni
 * Signature: (JLjava/nio/ByteBuffer;IJ)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_preprocessJni
  (JNIEnv *, jclass, jlong, jobject, jint, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    preprocessExJni
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_preprocessExJni
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    getDataSizeJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_getDataSizeJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    getDataJni
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_getDataJni
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    finishPreprocessJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_finishPreprocessJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    setFixLevelJni
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_setFixLevelJni
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    getFrameNumJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_getFrameNumJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    getCroppingSizeJni
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_getCroppingSizeJni
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    initializeJni
 * Signature: (Ljava/nio/ByteBuffer;IIIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_initializeJni
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    initializeExJni
 * Signature: (Ljava/nio/ByteBuffer;IIIIIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_initializeExJni
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    startJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_startJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    processJni
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_processJni
  (JNIEnv *, jclass, jlong, jobject, jobject, jint, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    processExJni
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_processExJni
  (JNIEnv *, jclass, jlong, jobject, jobject, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    getMatrixJni
 * Signature: (J[FI)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_getMatrixJni
  (JNIEnv *, jclass, jlong, jfloatArray, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    getMatrixExJni
 * Signature: (J[FI)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_getMatrixExJni
  (JNIEnv *, jclass, jlong, jfloatArray, jint);

/*
 * Class:     com_morphoinc_app_hyperlapse_engine_Engine2
 * Method:    finishJni
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_morphoinc_app_hyperlapse_engine_Engine2_finishJni
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
