// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./proto_v0_nodescriptor\BDILogProtos.proto
package com.htc.studio.bdi.log.schema;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *   Attribute Information
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
public final class Attribute extends Message {

  public static final String DEFAULT_LABEL = "";
  public static final String DEFAULT_EXTRA = "";

  @ProtoField(tag = 1, type = STRING)
  public final String label;

  /**
   * attribute label
   */
  @ProtoField(tag = 2, type = STRING)
  public final String extra;

  public Attribute(String label, String extra) {
    this.label = label;
    this.extra = extra;
  }

  private Attribute(Builder builder) {
    this(builder.label, builder.extra);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Attribute)) return false;
    Attribute o = (Attribute) other;
    return equals(label, o.label)
        && equals(extra, o.extra);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = label != null ? label.hashCode() : 0;
      result = result * 37 + (extra != null ? extra.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Attribute> {

    public String label;
    public String extra;

    public Builder() {
    }

    public Builder(Attribute message) {
      super(message);
      if (message == null) return;
      this.label = message.label;
      this.extra = message.extra;
    }

    public Builder label(String label) {
      this.label = label;
      return this;
    }

    /**
     * attribute label
     */
    public Builder extra(String extra) {
      this.extra = extra;
      return this;
    }

    @Override
    public Attribute build() {
      return new Attribute(this);
    }
  }
}
